### ISSUE TITLE
cannot open file 'xyz.zip': No such file or directory on publishWebService

### ISSUE THREAD

**Issue by jochenvanwylick** [Azure/Azure-MachineLearning-ClientLibrary-R#12]
Hi guys, great stuff this! I'm running a small experiment to see how `publishWebService` would deal with global variables, but I'm getting an error.

Here's the code - just trying to get a 'hello world' going:

````
install.packages(c("RCurl", "RJSONIO", "uuid", "jsonlite", "codetools", "base64enc", "httr", "data.table", "df2json", "rjson", "devtools"), repos = "http://cran.r-project.org")
devtools::install_github("Azure-MachineLearning-ClientLibrary-R", "Azure", subdir="AzureML")
require(AzureML)

counter <- 0;

greet <- function(name, age) {
  counter <<- counter + 1;
  return(c('hi there', name, ' your age is ', age, ' counter is @ ', counter))
}

wsid <- "my-ws-id"
authToken <- "my-auth-token"

response <- publishWebService("greet", "greetOnline", 
                              list("name"="string", "age"="int"), list("greeting"="string"), wsid, authToken)
````

The error message I'm getting:

````
Error in file(what, "rb") : cannot open the connection
In addition: Warning messages:
1: running command '"zip" -r9X "f0dc22a6610811e5a3343563995c4650" "f0dc22a6610811e5a3343563995c4650" ' had status 127 
2: In file(what, "rb") :
  cannot open file 'f0dc22a6610811e5a3343563995c4650.zip': No such file or directory
````

Now, I've checked and inside my current working directory - a new file *was* generated, called `f0dc22a6610811e5a3343563995c4650` - however, it's not called 'f0dc22a6610811e5a3343563995c4650.zip` ( with `.zip` at the end ). Could this be a bug?

I'm on windows, running R 3.2.1 and R studio. I'll start with updating the R version, but I'm sceptical whether that's going to be the problem.

**Comment by jochenvanwylick** [comment]
I updated R to 3.2.2 and installed RTools33, but that didn't seem to solve the problem.

**Comment by jochenvanwylick** [comment]
The problem is triggered by the `counter` variable in the outer scope. If I remove that line - I get a different error message.

**Comment by andrie** [comment]
We have rewritten this package.  Please use the new version at https://github.com/RevolutionAnalytics/AzureML.
